lexik_paybox_sample_call:
    path:     /
    defaults:
        _controller: "lexik_paybox.controller.sample::index"

lexik_paybox_sample_return:
    path:     /payment/return/{status}
    defaults:
        _controller: "lexik_paybox.controller.sample::return"
        status: error
    requirements:
        status: success|canceled|denied
